{% set data = load_setup_py_data() %}

package:
  name: {{ data['name'] }}
  version: {{ data['version'] }}

source:
  git_rev: {{ "v" + data['version'] }}
  git_url: https://github.com/CLARIAH/DANE-server.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rabbitmq-server

test:
  imports:
    -

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
